version: '3'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'me'
      MYSQL_PASSWORD: 'secret'
    ports:
      - 3306:3306
    volumes:
      - "~/opt/mysql:/var/lib/mysql"
    networks:
      app-network:
        aliases:
          - mysql

networks:
  app-network:
    driver: bridge